
export const cliniciansData= [
  {
    id: "1",
    userId: "user1",
    email: "jane.cooper@example.com",
    name: "Jane Cooper",
    practice: "Mindful Therapy",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    qualifications: "PhD, LPC",
    descriptions: "Specializes in cognitive behavioral therapy for adults",
    about: "10 years of experience helping clients with anxiety and depression",
    portfolioLink: "https://portfolio.example.com/jane",
    therapeuticMethods: ["CBT", "Mindfulness"],
    specialities: ["Anxiety", "Depression"],
    serviceTypes: ["Individual", "Couples"],
    agesServed: ["Adults", "Teens"],
    location: "New York, NY",
    availabilityDay: ["Monday", "Sunday"],
    availabilityTime: "Evening",
    telehealthOnly: false,
    createdAt: new Date("2020-01-15"),
    updatedAt: new Date("2023-05-20"),
  },
  {
    id: "2",
    userId: "user1",
    email: "jane.cooper@example.com",
    name: "Jane Cooper",
    practice: "Mindful Therapy",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    qualifications: "PhD, LPC",
    descriptions: "Specializes in cognitive behavioral therapy for adults",
    about: "10 years of experience helping clients with anxiety and depression",
    portfolioLink: "https://portfolio.example.com/jane",
    therapeuticMethods: ["CBT", "Mindfulness"],
    specialities: ["Anxiety", "Depression"],
    serviceTypes: ["Individual", "Couples"],
    agesServed: ["Adults", "Teens"],
    location: "New York, NY",
    availabilityDay: ["Monday-Friday"],
    availabilityTime: "9am-5pm",
    telehealthOnly: false,
    createdAt: new Date("2020-01-15"),
    updatedAt: new Date("2023-05-20"),
  },
  {
    id: "3",
    userId: "user1",
    email: "jane.cooper@example.com",
    name: "Jane Cooper",
    practice: "Mindful Therapy",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    qualifications: "PhD, LPC",
    descriptions: "Specializes in cognitive behavioral therapy for adults",
    about: "10 years of experience helping clients with anxiety and depression",
    portfolioLink: "https://portfolio.example.com/jane",
    therapeuticMethods: ["CBT", "Mindfulness"],
    specialities: ["Anxiety", "Depression"],
    serviceTypes: ["Individual", "Couples"],
    agesServed: ["Adults", "Teens"],
    location: "New York, NY",
    availabilityDay: "Monday-Friday",
    availabilityTime: ["9am-5pm"],
    telehealthOnly: false,
    createdAt: new Date("2020-01-15"),
    updatedAt: new Date("2023-05-20"),
  },
];
